version: "3"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    environment:
      REACT_APP_API_URL:
    ports:
      - "80:3000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"